name: Python CI

on:
  push:
    branches: [ "main" ]         # or your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Or whichever version your project uses

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Run tests (with coverage)
      - name: Run tests
        run: |
          pytest --cov=dlpdf --cov-report=term-missing
